import Head from 'next/head'
import Button from '../components/Button'
import React from 'react'



export default function Home() {
  return (
    <div className='flex flex-col justify-center items-center
    h-screen bg-slate-200 text-slate-400 '>
      <Head>
        <title>Oceano</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className=' text-lg md:text-5xl w-max-[1200px]'>
        <p>Entre e aproveite nosso sistema de cadastro</p>
      </div>
      <Button destiny="/list" text="Entrar" margin="6"/>
    </div>
  )
}
